/**
 * The live /tires catalog, reduced to what filtering and sorting need.
 * Scraped from continentaltire.com/tires on 2026-07-26. LIVE_COUNTS holds the
 * result total live itself reports for each single facet, so the filter tests
 * are a parity check against the real site, not against our own assumptions.
 */

export const CATALOG = [
  {
    slug: 'securecontact-aw',
    name: 'SecureContact AW',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Touring, All-Weather',
    rating: 5,
    reviews: 7,
    weight: 1,
  },
  {
    slug: 'truecontact-tour54',
    name: 'TrueContact Tour54',
    bestFor: 'Passenger, Crossover, Electric Vehicles, Touring, All-Season',
    rating: 4.3,
    reviews: 36,
    weight: 2,
  },
  {
    slug: 'terraincontact-at-2',
    name: 'TerrainContact A/T2',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, All-Terrain, All-Season',
    rating: 5,
    reviews: 1,
    weight: 3,
  },
  {
    slug: 'extremecontact-dws06-plus',
    name: 'ExtremeContact DWS06 Plus',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Ultra-High Performance, All-Season',
    rating: 4.6,
    reviews: 1043,
    weight: 4,
  },
  {
    slug: 'extremecontact-sport-02',
    name: 'ExtremeContact Sport02',
    bestFor: 'Passenger, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 4.7,
    reviews: 26,
    weight: 5,
  },
  {
    slug: 'purecontact-ls',
    name: 'PureContact LS',
    bestFor: 'Passenger, Crossover, Electric Vehicles, Touring, All-Season',
    rating: 4.6,
    reviews: 307,
    weight: 6,
  },
  {
    slug: 'truecontact-tour',
    name: 'TrueContact Tour',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Touring, All-Season',
    rating: 4.6,
    reviews: 376,
    weight: 7,
  },
  {
    slug: 'terraincontact-at',
    name: 'TerrainContact A/T',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, All-Terrain, All-Season',
    rating: 4.5,
    reviews: 211,
    weight: 8,
  },
  {
    slug: 'terraincontact-ht',
    name: 'TerrainContact H/T',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, Touring, All-Season',
    rating: 4.6,
    reviews: 224,
    weight: 9,
  },
  {
    slug: 'crosscontact-lx25',
    name: 'CrossContact LX25',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, Touring, All-Season',
    rating: 4.5,
    reviews: 400,
    weight: 10,
  },
  {
    slug: 'vikingcontact-7',
    name: 'VikingContact 7',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Touring, Winter',
    rating: 4.8,
    reviews: 67,
    weight: 11,
  },
  {
    slug: 'vancontact-winter',
    name: 'VanContact Winter',
    bestFor: 'Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, Winter',
    rating: 4.1,
    reviews: 40,
    weight: 12,
  },
  {
    slug: 'vikingcontact-8',
    name: 'VikingContact 8',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Touring, Winter',
    rating: 5,
    reviews: 2,
    weight: 13,
  },
  {
    slug: 'crosscontact-lx20',
    name: 'CrossContact LX20',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 3.7,
    reviews: 196,
    weight: 14,
  },
  {
    slug: 'crosscontact-lx-sport',
    name: 'CrossContact LXSport',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 2.3,
    reviews: 205,
    weight: 15,
  },
  {
    slug: 'premiumcontact-6',
    name: 'PremiumContact 6',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Touring, Summer',
    rating: 2.4,
    reviews: 14,
    weight: 16,
  },
  {
    slug: 'contisportcontact-5',
    name: 'ContiSportContact 5',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 2.5,
    reviews: 26,
    weight: 17,
  },
  {
    slug: 'controlcontact-tour-m-as',
    name: 'ControlContact TourM A/S',
    bestFor: 'Passenger, Crossover, Electric Vehicles, Touring, All-Season',
    rating: 4.3,
    reviews: 9,
    weight: 18,
  },
  {
    slug: 'vancofourseason',
    name: 'Vanco Four Season',
    bestFor: 'Fleet, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 3.5,
    reviews: 13,
    weight: 19,
  },
  {
    slug: 'wintercontact-ts850-p',
    name: 'WinterContact TS850 P',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Ultra-High Performance, Winter',
    rating: 0,
    reviews: 0,
    weight: 20,
  },
  {
    slug: 'contitrac',
    name: 'ContiTrac',
    bestFor: 'Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 4.1,
    reviews: 40,
    weight: 21,
  },
  {
    slug: 'wintercontact-ts-860-s',
    name: 'WinterContact TS 860 S',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Ultra-High Performance, Winter',
    rating: 0,
    reviews: 0,
    weight: 22,
  },
  {
    slug: 'contiwintercontact-ts830-p',
    name: 'ContiWinterContact TS830 P',
    bestFor: 'Passenger, Original Equipment, Electric Vehicles, Touring, Winter',
    rating: 3.7,
    reviews: 3,
    weight: 23,
  },
  {
    slug: 'controlcontact-tour-as-plus',
    name: 'ControlContact Tour A/S Plus',
    bestFor: 'Passenger, Electric Vehicles, Touring, All-Season',
    rating: 3.3,
    reviews: 29,
    weight: 24,
  },
  {
    slug: 'crosscontact-uhp',
    name: 'CrossContact UHP',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 5,
    reviews: 4,
    weight: 25,
  },
  {
    slug: 'crosscontact-rx',
    name: 'CrossContact RX',
    bestFor: 'Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 2.6,
    reviews: 92,
    weight: 26,
  },
  {
    slug: 'controlcontact-sport-srs-0',
    name: 'ControlContact Sport SRS+',
    bestFor: 'Passenger, Electric Vehicles, Ultra-High Performance, All-Season',
    rating: 3.7,
    reviews: 29,
    weight: 27,
  },
  {
    slug: 'vancontact-as-ultra',
    name: 'VanContact A/S Ultra',
    bestFor: 'Fleet, Electric Vehicles, Touring, All-Weather',
    rating: 5,
    reviews: 1,
    weight: 28,
  },
  {
    slug: 'extremecontact-force',
    name: 'ExtremeContact Force',
    bestFor: 'Passenger, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 5,
    reviews: 1,
    weight: 29,
  },
  {
    slug: 'contisportcontact-3',
    name: 'ContiSportContact 3',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 3,
    reviews: 6,
    weight: 30,
  },
  {
    slug: 'sportcontact-7',
    name: 'SportContact 7',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 3.2,
    reviews: 5,
    weight: 31,
  },
  {
    slug: 'crosscontact-atr',
    name: 'CrossContact ATR',
    bestFor: 'Light Truck/SUV, Original Equipment, Electric Vehicles, All-Terrain, All-Season',
    rating: 5,
    reviews: 4,
    weight: 32,
  },
  {
    slug: 'contisportcontact-5p',
    name: 'ContiSportContact 5P',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 3.1,
    reviews: 35,
    weight: 33,
  },
  {
    slug: 'procontact-rx',
    name: 'ProContact RX',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 2.6,
    reviews: 92,
    weight: 34,
  },
  {
    slug: 'crosscontact-lx',
    name: 'CrossContact LX',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 3.8,
    reviews: 69,
    weight: 35,
  },
  {
    slug: 'vancontact-as',
    name: 'VanContact A/S',
    bestFor: 'Fleet, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 3.8,
    reviews: 28,
    weight: 36,
  },
  {
    slug: 'procontact-tx10',
    name: 'ProContact TX10',
    bestFor: 'Passenger, Crossover, Original Equipment, Touring, All-Season',
    rating: 0,
    reviews: 0,
    weight: 37,
  },
  {
    slug: 'procontact-tx',
    name: 'ProContact TX',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 2.6,
    reviews: 142,
    weight: 38,
  },
  {
    slug: 'sportcontact-6',
    name: 'SportContact 6',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 2.4,
    reviews: 20,
    weight: 39,
  },
  {
    slug: 'procontact-gx',
    name: 'ProContact GX',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 1.9,
    reviews: 70,
    weight: 40,
  },
  {
    slug: 'contisportcontact-2',
    name: 'ContiSportContact 2',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 3.7,
    reviews: 15,
    weight: 41,
  },
  {
    slug: '4x4contact',
    name: '4x4 Contact',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 3.5,
    reviews: 53,
    weight: 42,
  },
  {
    slug: '4x4sportcontact',
    name: '4x4 SportContact',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Ultra-High Performance, Summer',
    rating: 0,
    reviews: 0,
    weight: 43,
  },
  {
    slug: 'contipremiumcontact-2',
    name: 'ContiPremiumContact 2',
    bestFor: 'Passenger, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    rating: 4.5,
    reviews: 19,
    weight: 44,
  },
  {
    slug: 'contiprocontact',
    name: 'ContiProContact',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    rating: 3.6,
    reviews: 408,
    weight: 45,
  },
  {
    slug: 'scontact',
    name: 'sContact',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Touring, All-Season',
    rating: 0,
    reviews: 0,
    weight: 46,
  },
];

/** Result totals live reports for each single facet. */
export const LIVE_COUNTS = {
  Fleet: 3,
  Passenger: 29,
  Crossover: 34,
  'Light Truck/SUV': 25,
  'Original Equipment': 26,
  'Ultra-High Performance': 15,
  Touring: 28,
  'All-Terrain': 3,
  'All-Season': 26,
  'All-Weather': 2,
  Summer: 12,
  Winter: 6,
};
