/**
 * The live /tires catalog, reduced to what filtering and sorting need.
 * Scraped from continentaltire.com on 2026-07-26. LIVE_COUNTS holds the result
 * total live reports per facet and LIVE_CATEGORY_ORDER the slug order each
 * category page renders, so the tests check parity with the real site rather
 * than with our own assumptions.
 */

export const CATALOG = [
  {
    slug: 'securecontact-aw',
    name: 'SecureContact AW',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Touring, All-Weather',
    facetWeights: 'Passenger:1, Crossover:1, Light Truck/SUV:1, Touring:1, All-Weather:1',
    rating: 5,
    reviews: 7,
    weight: 1,
    isNew: 'true',
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'truecontact-tour54',
    name: 'TrueContact Tour54',
    nameHtml: 'TrueContact Tour<sup>54</sup>',
    bestFor: 'Passenger, Crossover, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:2, Crossover:2, Touring:2, All-Season:1',
    rating: 4.3,
    reviews: 36,
    weight: 2,
  },
  {
    slug: 'terraincontact-at-2',
    name: 'TerrainContact A/T2',
    nameHtml: 'TerrainContact A/T<sup>2</sup>',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, All-Terrain, All-Season',
    facetWeights: 'Crossover:3, Light Truck/SUV:2, All-Terrain:1, All-Season:2',
    rating: 5,
    reviews: 1,
    weight: 3,
    isNew: 'true',
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'extremecontact-dws06-plus',
    name: 'ExtremeContact DWS06 Plus',
    nameHtml: 'ExtremeContact DWS<sup>06 Plus</sup>',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Ultra-High Performance, All-Season',
    facetWeights: 'Passenger:3, Crossover:4, Light Truck/SUV:3, Ultra-High Performance:1, All-Season:3',
    rating: 4.6,
    reviews: 1043,
    weight: 4,
  },
  {
    slug: 'extremecontact-sport-02',
    name: 'ExtremeContact Sport02',
    nameHtml: 'ExtremeContact Sport<sup>02</sup>',
    bestFor: 'Passenger, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:4, Ultra-High Performance:2, Summer:1',
    rating: 4.7,
    reviews: 26,
    weight: 5,
  },
  {
    slug: 'purecontact-ls',
    name: 'PureContact LS',
    bestFor: 'Passenger, Crossover, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:5, Crossover:5, Touring:3, All-Season:4',
    rating: 4.6,
    reviews: 307,
    weight: 6,
  },
  {
    slug: 'truecontact-tour',
    name: 'TrueContact Tour',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:6, Crossover:6, Light Truck/SUV:4, Touring:4, All-Season:5',
    rating: 4.6,
    reviews: 376,
    weight: 7,
  },
  {
    slug: 'terraincontact-at',
    name: 'TerrainContact A/T',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, All-Terrain, All-Season',
    facetWeights: 'Crossover:7, Light Truck/SUV:5, All-Terrain:2, All-Season:6',
    rating: 4.5,
    reviews: 211,
    weight: 8,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'terraincontact-ht',
    name: 'TerrainContact H/T',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Crossover:8, Light Truck/SUV:6, Touring:5, All-Season:7',
    rating: 4.6,
    reviews: 224,
    weight: 9,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'crosscontact-lx25',
    name: 'CrossContact LX25',
    nameHtml: 'CrossContact LX<sup>25</sup>',
    bestFor: 'Crossover, Light Truck/SUV, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Crossover:9, Light Truck/SUV:7, Touring:6, All-Season:8',
    rating: 4.5,
    reviews: 400,
    weight: 10,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'vikingcontact-7',
    name: 'VikingContact 7',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Touring, Winter',
    facetWeights: 'Passenger:7, Crossover:10, Light Truck/SUV:8, Touring:7, Winter:1',
    rating: 4.8,
    reviews: 67,
    weight: 11,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'vancontact-winter',
    name: 'VanContact Winter',
    bestFor: 'Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, Winter',
    facetWeights: 'Light Truck/SUV:9, Original Equipment:1, Touring:9, Winter:3',
    rating: 4.1,
    reviews: 40,
    weight: 12,
  },
  {
    slug: 'vikingcontact-8',
    name: 'VikingContact 8',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Electric Vehicles, Touring, Winter',
    facetWeights: 'Passenger:8, Crossover:11, Light Truck/SUV:10, Touring:8, Winter:2',
    rating: 5,
    reviews: 2,
    weight: 13,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'crosscontact-lx20',
    name: 'CrossContact LX20',
    nameHtml: 'CrossContact LX<sup>20</sup>',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Crossover:12, Light Truck/SUV:11, Original Equipment:2, Touring:10, All-Season:9',
    rating: 3.7,
    reviews: 196,
    weight: 14,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'crosscontact-lx-sport',
    name: 'CrossContact LXSport',
    nameHtml: 'CrossContact LX<sup>Sport</sup>',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Crossover:13, Light Truck/SUV:12, Original Equipment:3, Touring:12, All-Season:10',
    rating: 2.3,
    reviews: 205,
    weight: 15,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'premiumcontact-6',
    name: 'PremiumContact 6',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Touring, Summer',
    facetWeights: 'Passenger:9, Crossover:14, Light Truck/SUV:13, Original Equipment:4, Touring:11, Summer:2',
    rating: 2.4,
    reviews: 14,
    weight: 16,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'contisportcontact-5',
    name: 'ContiSportContact 5',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:10, Crossover:15, Light Truck/SUV:14, Original Equipment:5, Ultra-High Performance:3, Summer:3',
    rating: 2.5,
    reviews: 26,
    weight: 17,
  },
  {
    slug: 'controlcontact-tour-m-as',
    name: 'ControlContact TourM A/S',
    nameHtml: 'ControlContact Tour<sup>M</sup> A/S',
    bestFor: 'Passenger, Crossover, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:11, Crossover:16, Touring:13, All-Season:11',
    rating: 4.3,
    reviews: 9,
    weight: 18,
  },
  {
    slug: 'vancofourseason',
    name: 'Vanco Four Season',
    bestFor: 'Fleet, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Original Equipment:6, Touring:14, All-Season:12',
    rating: 3.5,
    reviews: 13,
    weight: 19,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'wintercontact-ts850-p',
    name: 'WinterContact TS850 P',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Ultra-High Performance, Winter',
    facetWeights: 'Passenger:12, Crossover:17, Light Truck/SUV:15, Ultra-High Performance:4, Winter:4',
    rating: 0,
    reviews: 0,
    weight: 20,
  },
  {
    slug: 'contitrac',
    name: 'ContiTrac',
    bestFor: 'Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Light Truck/SUV:16, Original Equipment:7, Touring:15, All-Season:13',
    rating: 4.1,
    reviews: 40,
    weight: 21,
  },
  {
    slug: 'wintercontact-ts-860-s',
    name: 'WinterContact TS 860 S',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Ultra-High Performance, Winter',
    facetWeights: 'Passenger:14, Crossover:18, Light Truck/SUV:17, Ultra-High Performance:5, Winter:5',
    rating: 0,
    reviews: 0,
    weight: 22,
  },
  {
    slug: 'contiwintercontact-ts830-p',
    name: 'ContiWinterContact TS830 P',
    bestFor: 'Passenger, Original Equipment, Electric Vehicles, Touring, Winter',
    facetWeights: 'Passenger:13, Original Equipment:8, Touring:16, Winter:6',
    rating: 3.7,
    reviews: 3,
    weight: 23,
  },
  {
    slug: 'controlcontact-tour-as-plus',
    name: 'ControlContact Tour A/S Plus',
    nameHtml: 'ControlContact Tour <sup>A/S Plus</sup>',
    bestFor: 'Passenger, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:15, Touring:17, All-Season:14',
    rating: 3.3,
    reviews: 29,
    weight: 24,
  },
  {
    slug: 'crosscontact-uhp',
    name: 'CrossContact UHP',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Crossover:19, Light Truck/SUV:18, Original Equipment:9, Ultra-High Performance:6, Summer:4',
    rating: 5,
    reviews: 4,
    weight: 25,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'crosscontact-rx',
    name: 'CrossContact RX',
    bestFor: 'Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Crossover:20, Original Equipment:10, Touring:18, All-Season:15',
    rating: 2.6,
    reviews: 92,
    weight: 26,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'controlcontact-sport-srs-0',
    name: 'ControlContact Sport SRS+',
    bestFor: 'Passenger, Electric Vehicles, Ultra-High Performance, All-Season',
    facetWeights: 'Passenger:16, Ultra-High Performance:7, All-Season:16',
    rating: 3.7,
    reviews: 29,
    weight: 27,
  },
  {
    slug: 'vancontact-as-ultra',
    name: 'VanContact A/S Ultra',
    bestFor: 'Fleet, Electric Vehicles, Touring, All-Weather',
    facetWeights: 'Touring:19, All-Weather:2',
    rating: 5,
    reviews: 1,
    weight: 28,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'extremecontact-force',
    name: 'ExtremeContact Force',
    bestFor: 'Passenger, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:17, Ultra-High Performance:8, Summer:5',
    rating: 5,
    reviews: 1,
    weight: 29,
  },
  {
    slug: 'contisportcontact-3',
    name: 'ContiSportContact 3',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:18, Crossover:21, Original Equipment:11, Ultra-High Performance:9, Summer:6',
    rating: 3,
    reviews: 6,
    weight: 30,
  },
  {
    slug: 'sportcontact-7',
    name: 'SportContact 7',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:19, Crossover:22, Light Truck/SUV:19, Original Equipment:12, Ultra-High Performance:10, Summer:7',
    rating: 3.2,
    reviews: 5,
    weight: 31,
  },
  {
    slug: 'crosscontact-atr',
    name: 'CrossContact ATR',
    bestFor: 'Light Truck/SUV, Original Equipment, Electric Vehicles, All-Terrain, All-Season',
    facetWeights: 'Light Truck/SUV:20, Original Equipment:13, All-Terrain:3, All-Season:17',
    rating: 5,
    reviews: 4,
    weight: 32,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'contisportcontact-5p',
    name: 'ContiSportContact 5P',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:20, Crossover:23, Original Equipment:14, Ultra-High Performance:11, Summer:8',
    rating: 3.1,
    reviews: 35,
    weight: 33,
  },
  {
    slug: 'procontact-rx',
    name: 'ProContact RX',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:21, Crossover:24, Original Equipment:15, Touring:20, All-Season:18',
    rating: 2.6,
    reviews: 92,
    weight: 34,
  },
  {
    slug: 'crosscontact-lx',
    name: 'CrossContact LX',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Crossover:25, Light Truck/SUV:21, Original Equipment:16, Touring:21, All-Season:19',
    rating: 3.8,
    reviews: 69,
    weight: 35,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'vancontact-as',
    name: 'VanContact A/S',
    bestFor: 'Fleet, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Original Equipment:17, Touring:22, All-Season:20',
    rating: 3.8,
    reviews: 28,
    weight: 36,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'procontact-tx10',
    name: 'ProContact TX10',
    nameHtml: 'ProContact TX<sup>10</sup>',
    bestFor: 'Passenger, Crossover, Original Equipment, Touring, All-Season',
    facetWeights: 'Passenger:23, Crossover:26, Original Equipment:19, Touring:24, All-Season:22',
    rating: 0,
    reviews: 0,
    weight: 37,
  },
  {
    slug: 'procontact-tx',
    name: 'ProContact TX',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:22, Crossover:27, Original Equipment:18, Touring:23, All-Season:21',
    rating: 2.6,
    reviews: 142,
    weight: 38,
  },
  {
    slug: 'sportcontact-6',
    name: 'SportContact 6',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:24, Crossover:28, Light Truck/SUV:22, Original Equipment:20, Ultra-High Performance:12, Summer:9',
    rating: 2.4,
    reviews: 20,
    weight: 39,
  },
  {
    slug: 'procontact-gx',
    name: 'ProContact GX',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:25, Crossover:29, Original Equipment:21, Touring:25, All-Season:23',
    rating: 1.9,
    reviews: 70,
    weight: 40,
  },
  {
    slug: 'contisportcontact-2',
    name: 'ContiSportContact 2',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:26, Crossover:30, Original Equipment:22, Ultra-High Performance:13, Summer:10',
    rating: 3.7,
    reviews: 15,
    weight: 41,
  },
  {
    slug: '4x4contact',
    name: '4x4 Contact',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Crossover:32, Light Truck/SUV:23, Original Equipment:23, Touring:26, All-Season:24',
    rating: 3.5,
    reviews: 53,
    weight: 42,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: '4x4sportcontact',
    name: '4x4 SportContact',
    bestFor: 'Crossover, Light Truck/SUV, Original Equipment, Ultra-High Performance, Summer',
    facetWeights: 'Crossover:31, Light Truck/SUV:24, Original Equipment:24, Ultra-High Performance:14, Summer:11',
    rating: 0,
    reviews: 0,
    weight: 43,
    promo: '$110 Rebate Offer',
    promoPath: '/promotion',
  },
  {
    slug: 'contipremiumcontact-2',
    name: 'ContiPremiumContact 2',
    bestFor: 'Passenger, Original Equipment, Electric Vehicles, Ultra-High Performance, Summer',
    facetWeights: 'Passenger:27, Original Equipment:25, Ultra-High Performance:15, Summer:12',
    rating: 4.5,
    reviews: 19,
    weight: 44,
  },
  {
    slug: 'contiprocontact',
    name: 'ContiProContact',
    bestFor: 'Passenger, Crossover, Original Equipment, Electric Vehicles, Touring, All-Season',
    facetWeights: 'Passenger:28, Crossover:33, Original Equipment:26, Touring:27, All-Season:25',
    rating: 3.6,
    reviews: 408,
    weight: 45,
  },
  {
    slug: 'scontact',
    name: 'sContact',
    bestFor: 'Passenger, Crossover, Light Truck/SUV, Touring, All-Season',
    facetWeights: 'Passenger:29, Crossover:34, Light Truck/SUV:25, Touring:28, All-Season:26',
    rating: 0,
    reviews: 0,
    weight: 46,
  },
];

/** Result totals live reports for each single facet. */
export const LIVE_COUNTS = {
  Fleet: 3,
  Passenger: 29,
  Crossover: 34,
  'Light Truck/SUV': 25,
  'Original Equipment': 26,
  'Ultra-High Performance': 15,
  Touring: 28,
  'All-Terrain': 3,
  'All-Season': 26,
  'All-Weather': 2,
  Summer: 12,
  Winter: 6,
};

/** The slug order each live category page renders, in its own editorial weight. */
export const LIVE_CATEGORY_ORDER = {
  Passenger: [
    'securecontact-aw', 'truecontact-tour54', 'extremecontact-dws06-plus',
    'extremecontact-sport-02', 'purecontact-ls', 'truecontact-tour',
    'vikingcontact-7', 'vikingcontact-8', 'premiumcontact-6',
    'contisportcontact-5', 'controlcontact-tour-m-as', 'wintercontact-ts850-p',
    'contiwintercontact-ts830-p', 'wintercontact-ts-860-s', 'controlcontact-tour-as-plus',
    'controlcontact-sport-srs-0', 'extremecontact-force', 'contisportcontact-3',
    'sportcontact-7', 'contisportcontact-5p', 'procontact-rx',
    'procontact-tx', 'procontact-tx10', 'sportcontact-6',
    'procontact-gx', 'contisportcontact-2', 'contipremiumcontact-2',
    'contiprocontact', 'scontact',
  ],
  Crossover: [
    'securecontact-aw', 'truecontact-tour54', 'terraincontact-at-2',
    'extremecontact-dws06-plus', 'purecontact-ls', 'truecontact-tour',
    'terraincontact-at', 'terraincontact-ht', 'crosscontact-lx25',
    'vikingcontact-7', 'vikingcontact-8', 'crosscontact-lx20',
    'crosscontact-lx-sport', 'premiumcontact-6', 'contisportcontact-5',
    'controlcontact-tour-m-as', 'wintercontact-ts850-p', 'wintercontact-ts-860-s',
    'crosscontact-uhp', 'crosscontact-rx', 'contisportcontact-3',
    'sportcontact-7', 'contisportcontact-5p', 'procontact-rx',
    'crosscontact-lx', 'procontact-tx10', 'procontact-tx',
    'sportcontact-6', 'procontact-gx', 'contisportcontact-2',
    '4x4sportcontact', '4x4contact', 'contiprocontact',
    'scontact',
  ],
  'Light Truck/SUV': [
    'securecontact-aw', 'terraincontact-at-2', 'extremecontact-dws06-plus',
    'truecontact-tour', 'terraincontact-at', 'terraincontact-ht',
    'crosscontact-lx25', 'vikingcontact-7', 'vancontact-winter',
    'vikingcontact-8', 'crosscontact-lx20', 'crosscontact-lx-sport',
    'premiumcontact-6', 'contisportcontact-5', 'wintercontact-ts850-p',
    'contitrac', 'wintercontact-ts-860-s', 'crosscontact-uhp',
    'sportcontact-7', 'crosscontact-atr', 'crosscontact-lx',
    'sportcontact-6', '4x4contact', '4x4sportcontact',
    'scontact',
  ],
  'Original Equipment': [
    'vancontact-winter', 'crosscontact-lx20', 'crosscontact-lx-sport',
    'premiumcontact-6', 'contisportcontact-5', 'vancofourseason',
    'contitrac', 'contiwintercontact-ts830-p', 'crosscontact-uhp',
    'crosscontact-rx', 'contisportcontact-3', 'sportcontact-7',
    'crosscontact-atr', 'contisportcontact-5p', 'procontact-rx',
    'crosscontact-lx', 'vancontact-as', 'procontact-tx',
    'procontact-tx10', 'sportcontact-6', 'procontact-gx',
    'contisportcontact-2', '4x4contact', '4x4sportcontact',
    'contipremiumcontact-2', 'contiprocontact',
  ],
  Touring: [
    'securecontact-aw', 'truecontact-tour54', 'purecontact-ls',
    'truecontact-tour', 'terraincontact-ht', 'crosscontact-lx25',
    'vikingcontact-7', 'vikingcontact-8', 'vancontact-winter',
    'crosscontact-lx20', 'premiumcontact-6', 'crosscontact-lx-sport',
    'controlcontact-tour-m-as', 'vancofourseason', 'contitrac',
    'contiwintercontact-ts830-p', 'controlcontact-tour-as-plus', 'crosscontact-rx',
    'vancontact-as-ultra', 'procontact-rx', 'crosscontact-lx',
    'vancontact-as', 'procontact-tx', 'procontact-tx10',
    'procontact-gx', '4x4contact', 'contiprocontact',
    'scontact',
  ],
  'All-Terrain': [
    'terraincontact-at-2', 'terraincontact-at', 'crosscontact-atr',
  ],
  'Ultra-High Performance': [
    'extremecontact-dws06-plus', 'extremecontact-sport-02', 'contisportcontact-5',
    'wintercontact-ts850-p', 'wintercontact-ts-860-s', 'crosscontact-uhp',
    'controlcontact-sport-srs-0', 'extremecontact-force', 'contisportcontact-3',
    'sportcontact-7', 'contisportcontact-5p', 'sportcontact-6',
    'contisportcontact-2', '4x4sportcontact', 'contipremiumcontact-2',
  ],
  'All-Season': [
    'truecontact-tour54', 'terraincontact-at-2', 'extremecontact-dws06-plus',
    'purecontact-ls', 'truecontact-tour', 'terraincontact-at',
    'terraincontact-ht', 'crosscontact-lx25', 'crosscontact-lx20',
    'crosscontact-lx-sport', 'controlcontact-tour-m-as', 'vancofourseason',
    'contitrac', 'controlcontact-tour-as-plus', 'crosscontact-rx',
    'controlcontact-sport-srs-0', 'crosscontact-atr', 'procontact-rx',
    'crosscontact-lx', 'vancontact-as', 'procontact-tx',
    'procontact-tx10', 'procontact-gx', '4x4contact',
    'contiprocontact', 'scontact',
  ],
  'All-Weather': [
    'securecontact-aw', 'vancontact-as-ultra',
  ],
  Summer: [
    'extremecontact-sport-02', 'premiumcontact-6', 'contisportcontact-5',
    'crosscontact-uhp', 'extremecontact-force', 'contisportcontact-3',
    'sportcontact-7', 'contisportcontact-5p', 'sportcontact-6',
    'contisportcontact-2', '4x4sportcontact', 'contipremiumcontact-2',
  ],
  Winter: [
    'vikingcontact-7', 'vikingcontact-8', 'vancontact-winter',
    'wintercontact-ts850-p', 'wintercontact-ts-860-s', 'contiwintercontact-ts830-p',
  ],
};
